# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x03tms\"\x7f\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1f\n\x06status\x18\x04 \x01(\x0e\x32\x0f.tms.TaskStatus\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\"\x12\n\x10ListTasksRequest\"-\n\x11ListTasksResponse\x12\x18\n\x05tasks\x18\x01 \x03(\x0b\x32\t.tms.Task\"\x1c\n\x0eGetTaskRequest\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x0fGetTaskResponse\x12\x17\n\x04task\x18\x01 \x01(\x0b\x32\t.tms.Task\"X\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1f\n\x06status\x18\x03 \x01(\x0e\x32\x0f.tms.TaskStatus\"-\n\x12\x43reateTaskResponse\x12\x17\n\x04task\x18\x01 \x01(\x0b\x32\t.tms.Task\"d\n\x11UpdateTaskRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1f\n\x06status\x18\x04 \x01(\x0e\x32\x0f.tms.TaskStatus\"-\n\x12UpdateTaskResponse\x12\x17\n\x04task\x18\x01 \x01(\x0b\x32\t.tms.Task\"\x1f\n\x11\x44\x65leteTaskRequest\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x12\x44\x65leteTaskResponse\x12\n\n\x02ok\x18\x01 \x01(\x08*^\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x08\n\x04Open\x10\x01\x12\x08\n\x04ToDo\x10\x02\x12\t\n\x05\x44oing\x10\x03\x12\x08\n\x04\x44one\x10\x04\x12\n\n\x06\x43losed\x10\x05\x32\xbc\x02\n\x0bTaskService\x12:\n\tListTasks\x12\x15.tms.ListTasksRequest\x1a\x16.tms.ListTasksResponse\x12\x34\n\x07GetTask\x12\x13.tms.GetTaskRequest\x1a\x14.tms.GetTaskResponse\x12=\n\nCreateTask\x12\x16.tms.CreateTaskRequest\x1a\x17.tms.CreateTaskResponse\x12=\n\nUpdateTask\x12\x16.tms.UpdateTaskRequest\x1a\x17.tms.UpdateTaskResponse\x12=\n\nDeleteTask\x12\x16.tms.DeleteTaskRequest\x1a\x17.tms.DeleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKSTATUS']._serialized_start=643
  _globals['_TASKSTATUS']._serialized_end=737
  _globals['_TASK']._serialized_start=20
  _globals['_TASK']._serialized_end=147
  _globals['_LISTTASKSREQUEST']._serialized_start=149
  _globals['_LISTTASKSREQUEST']._serialized_end=167
  _globals['_LISTTASKSRESPONSE']._serialized_start=169
  _globals['_LISTTASKSRESPONSE']._serialized_end=214
  _globals['_GETTASKREQUEST']._serialized_start=216
  _globals['_GETTASKREQUEST']._serialized_end=244
  _globals['_GETTASKRESPONSE']._serialized_start=246
  _globals['_GETTASKRESPONSE']._serialized_end=288
  _globals['_CREATETASKREQUEST']._serialized_start=290
  _globals['_CREATETASKREQUEST']._serialized_end=378
  _globals['_CREATETASKRESPONSE']._serialized_start=380
  _globals['_CREATETASKRESPONSE']._serialized_end=425
  _globals['_UPDATETASKREQUEST']._serialized_start=427
  _globals['_UPDATETASKREQUEST']._serialized_end=527
  _globals['_UPDATETASKRESPONSE']._serialized_start=529
  _globals['_UPDATETASKRESPONSE']._serialized_end=574
  _globals['_DELETETASKREQUEST']._serialized_start=576
  _globals['_DELETETASKREQUEST']._serialized_end=607
  _globals['_DELETETASKRESPONSE']._serialized_start=609
  _globals['_DELETETASKRESPONSE']._serialized_end=641
  _globals['_TASKSERVICE']._serialized_start=740
  _globals['_TASKSERVICE']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
